### PR TITLE
Continuous integration framework

### PR DESCRIPTION
**Pull request by rosinec**
This PR introduces a demo of how the periodical checking tool for bio.tools annotations could look like.

### CODE REVIEW

**Comment by LucieLamothe** [comment]
Hi @rosinec, 
Thank you for your PR! I will merge it right away. 
As of right now we cannot implement periodically because that would require an online publicly available SPARQL endpoint. But once it's ready we will be looking to implement something like this.

**Comment by krab1k** [comment]
@LucieLamothe Regarding the SPARQL endpoint, what is required technically? We have the infrastructure to host it so maybe we can help with setting that up. Would that help?

**Comment by LucieLamothe** [comment]
@krab1k 
Before the BH it was primarily an issue of timing, we didn't have time to set it up for everyone to use it with the short timing we had. We already have one for an old version of EDAM [here](https://130.226.25.41/sparql) hosted in France, we just need to set it up with @albangaignard help. But I'm not aware of all the restriction maybe it would help :) We need to organize a hacking session with the team to figure it out.

**Comment by krab1k** [comment]
Ok, sure. Once we have that with the bio.tools dump updated regularly, we can follow up with these automated checks. In any case, if there is a need for some technical help or additional infrastructure, let us know. :-)

**Pull request merged**
