### PR TITLE
Add workflowhub_galaxy_biotools.py

### PR DESCRIPTION
**Pull request by supernord**
Adding python script that:
- Collects workflow metadata from BioCommons WorkflowHub space: https://workflowhub.eu/programmes/8/workflows
- Collects Galaxy ID and biotools ID from Galaxy AU API

### CODE REVIEW

**Comment by supernord** [comment]
@hmenager, @matuskalas , @LucieLamothe 
please let me know if you have any suggestions to improve the script as well 😃

**Comment by hmenager** [comment]
Thank you @supernord !

Two suggestions:
- add a requirements file. I think at least requests is not part of standard library (or is it now?)
- results serialisation: I had a discussion yesterday with @albangaignard : the easiest way to represent these data is with BioSchemas: each workflow being a ComputationalWorkflow (https://bioschemas.org/types/ComputationalWorkflow/1.0-RELEASE), and each tool it uses being pointed by a hasPart (https://schema.org/hasPart) property that points to the right bio.tools identifier.

Example code that generates bioschemas file from bio.tools is available here: https://github.com/bio-tools/content-ecosystem-utils/blob/main/scripts/bioschemas/biotools_to_bioschemas.py

**Comment by supernord** [comment]
@hmenager - added requirements file 

should I complete the script to pull biotools metadata via the API as well?

**Comment by supernord** [comment]
@hmenager - I updated the script and it now produces the Galaxy IDs, and includes the workflow source + biotools ID, if available

**Comment by supernord** [comment]
included some counts too 😄

**Review by hmenager — APPROVED** [review]

**Pull request merged**
